{{-- resources/views/dashboard/_loading.blade.php --}}
{{--
    The branded wait that covers the page while the dashboard body is fetched.

    Presented as a floating card over a dimmed page, borrowing the app's own
    modal language (.remedi-modal's scrim and panel shadow) so it reads as the
    same kind of object as the logout and confirm dialogs rather than a second
    invented style.

    It is NOT a real dialog: no role="dialog", no aria-modal, no focus trap.
    Nothing here needs answering -- it is a status that happens to be centred,
    and trapping focus in it would strand a keyboard user for ten seconds. The
    failure panel below has real buttons, and they are reachable by Tab because
    of that choice.

    Everything is driven by classes on #dashboardRoot so the shell script can
    move between states without rebuilding the markup.
--}}
{{-- The page's own shape, behind the scrim. Reused from the in-app
     navigation skeleton rather than written twice -- one definition means the
     two can never drift out of step with the dashboard's real proportions.
     aria-hidden lives on the partial: it is scenery, and the role="status"
     inside the card is what actually reports the wait. --}}
@include('partials._page-skeleton')

<div class="dash-loader" id="dashLoader">
    <div class="dash-loader__card">
        {{-- Faint pharmacy motifs, clipped to the card. Purely decorative and
             aria-hidden: they carry no information and would only add noise to
             a screen reader. --}}
        <svg class="dash-loader__motifs" viewBox="0 0 560 420" preserveAspectRatio="xMidYMid slice"
             aria-hidden="true" focusable="false">
            <g fill="none" stroke="currentColor" stroke-width="2">
                <circle cx="64" cy="58" r="14"/>
                <circle cx="86" cy="74" r="14"/>
                <circle cx="486" cy="96" r="12"/>
                <circle cx="505" cy="111" r="12"/>
                <circle cx="250" cy="382" r="11"/>
                <path d="M120 300h20M130 290v20"/>
                <path d="M470 286h18M479 277v18"/>
                <path d="M40 196c11-7 22-7 33 0s22 7 33 0"/>
                <path d="M430 366c11-7 22-7 33 0s22 7 33 0"/>
                <rect x="446" y="196" width="38" height="22" rx="11" transform="rotate(-32 465 207)"/>
                <rect x="52" y="330" width="38" height="22" rx="11" transform="rotate(24 71 341)"/>
            </g>
        </svg>

        {{-- The soft wave along the card's bottom edge. --}}
        <svg class="dash-loader__wave" viewBox="0 0 1440 220" preserveAspectRatio="none"
             aria-hidden="true" focusable="false">
            <path d="M0 96c220 60 420 60 640 18s520-58 800 22v84H0z" fill="currentColor"/>
        </svg>

        <div class="dash-loader__stage">
            {{-- The ring. An indeterminate arc, not a progress bar: the server
                 reports no progress, so a filling bar would be a fabrication. --}}
            <div class="dash-loader__ring">
                <svg viewBox="0 0 120 120" aria-hidden="true" focusable="false">
                    <circle class="dash-loader__track" cx="60" cy="60" r="54"/>
                    <circle class="dash-loader__arc" cx="60" cy="60" r="54"/>
                </svg>
                {{-- INLINED, not <img src="logo.png">, and that is the whole
                     point of it.

                     `php artisan serve` is single-threaded: it handles one
                     request at a time. The dashboard body takes 5-12s, so for
                     that entire window the dev server cannot serve anything
                     else -- including a 278KB PNG. Measured: logo.png, a
                     static file, took 2.83s and landed at the exact moment the
                     dashboard request finished, i.e. just as this loader was
                     being destroyed. The ring spun empty for the whole wait.

                     It looked fine on localhost only because the browser had
                     the file cached from the sidebar. On 127.0.0.1 -- a
                     DIFFERENT ORIGIN with its own empty cache, the same two-
                     hosts trap that bit the cached route URLs -- there was
                     nothing to fall back on and the logo simply never
                     appeared.

                     A loading screen must not depend on a request to the
                     server it is waiting for. logo-mark.webp is a 160px
                     derivative of logo.png (7.6KB, ~10KB inlined) generated by
                     `php artisan logo:mark` -- regenerate it if logo.png ever
                     changes, or this will quietly show the old artwork.

                     width/height match the CSS so the ring cannot reflow.
                     alt="" because the mark is decorative here: the heading
                     beside it already says what is happening. --}}
                <img src="data:image/webp;base64,{{ base64_encode(file_get_contents(public_path('logo-mark.webp'))) }}"
                     alt="" width="76" height="76" class="dash-loader__logo">
            </div>

            {{-- One live region for the whole wait. role="status" is polite, so
                 it waits for a pause instead of cutting across the user. --}}
            <div class="dash-loader__say" role="status">
                <h3 class="dash-loader__title" id="dashLoaderTitle">Loading Dashboard</h3>
                <p class="dash-loader__sub" id="dashLoaderSub">Please wait while we prepare your data&hellip;</p>
            </div>

            <div class="dash-loader__dots" aria-hidden="true">
                <span></span><span></span><span></span>
            </div>
        </div>

        {{-- Failure state. A ten-second request that dies must not leave a ring
             turning forever, so the loader owns its own dead end: what
             happened, and two ways out that do not require knowing the URL. --}}
        <div class="dash-loader__failed" id="dashLoaderFailed" hidden>
            <div class="dash-loader__failed-icon"><i class="ti ti-plug-connected-x" aria-hidden="true"></i></div>
            <h3 class="dash-loader__title">Couldn&rsquo;t load the dashboard</h3>
            <p class="dash-loader__sub" id="dashLoaderError">The request didn&rsquo;t come back.</p>
            <div class="dash-loader__actions">
                <button type="button" class="btn btn-primary" id="dashRetry">
                    <i class="ti ti-refresh" aria-hidden="true"></i> Try again
                </button>
                <a class="btn btn-secondary" href="{{ route('dashboard', ['full' => 1]) }}">
                    Load the full page
                </a>
            </div>
        </div>
    </div>
</div>
