<?php

namespace App\Http\Controllers;

use App\Models\AuditTrail;
use Illuminate\Support\Facades\DB;

class BackupController extends Controller
{
    /**
     * The tables a backup actually needs to carry.
     *
     * `sales_history` (113,960 rows) and `inventory_receipts` (42,542 rows)
     * are deliberately excluded -- both are, per REMEDI.md/CLAUDE.md, IMPORTED
     * data with their own source of truth already sitting outside the
     * database: `database/data/Sales_Records_4Year.csv` (regenerated by
     * `database/data/generate_sales_history.py`, loaded by
     * `SalesHistorySeeder`) and the repo-root `Transaction_Records_Seed.csv`
     * (loaded by `InventoryReceiptSeeder`). Neither is written by the app
     * itself, so neither can be LOST by the app -- only by losing the CSV,
     * which this backup does not carry either way. Including them would
     * multiply the dump by roughly 7x for no data actually at risk, which on
     * a serverless request is the difference between a backup that finishes
     * in a couple of seconds and one that risks the platform's own timeout.
     *
     * `demand_forecasts` / `sales_forecasts` / `forecast_accuracy` ARE
     * included even though they too can be regenerated (`forecast:generate`,
     * `sales-forecast:generate`) -- unlike the two CSVs above, regenerating
     * them costs real compute time (a Python SARIMA fit per product) rather
     * than being a re-import, so losing them is a cost worth backing up
     * against.
     *
     * Deliberately excluded for a different reason: `cache`, `cache_locks`,
     * `sessions`, `password_reset_tokens`, `personal_access_tokens`,
     * `failed_jobs`, `migrations` -- framework bookkeeping and ephemeral
     * state, not business data. Restoring a stashed session or a stale
     * password-reset token later would be a security bug, not a recovery.
     */
    private const BACKUP_TABLES = [
        'users', 'categories', 'products', 'product_batches',
        'sales', 'sale_items', 'audit_trails',
        'demand_forecasts', 'sales_forecasts', 'forecast_accuracy',
    ];

    /**
     * Stream a plain-SQL dump of the tables above -- schema (DROP + CREATE,
     * from SHOW CREATE TABLE, so it carries indexes/AUTO_INCREMENT/collation
     * exactly as they exist) followed by INSERT statements, chunked so the
     * ~28,500 rows involved are never all held in memory at once.
     *
     * Streamed directly to the response rather than written to a file first:
     * this app also runs on a serverless PHP runtime (Vercel) where only
     * /tmp is writable -- see AppServiceProvider's excel/dompdf temp-path
     * override for the same constraint biting a different feature. A backup
     * is exactly the kind of file that should never touch server disk anyway.
     *
     * Restore is intentionally NOT built here -- a self-service restore
     * button is the one control on this page that can destroy live
     * production data, and this repo's practice throughout (see the
     * destructive-action guards in DestructiveGuardsTest) is to require a
     * person with real database access for anything at that end of the risk
     * scale, not a confirm dialog.
     */
    public function download()
    {
        $tables = self::BACKUP_TABLES;
        $filename = 'remedi-backup-'.now()->format('Y-m-d_His').'.sql';

        AuditTrail::log('Viewed', 'Downloaded database backup ('.count($tables).' tables: '.implode(', ', $tables).')');

        return response()->streamDownload(function () use ($tables) {
            echo "-- REMEDI database backup\n";
            echo '-- Generated '.now()->toDateTimeString()." (Asia/Manila)\n";
            echo '-- Tables: '.implode(', ', $tables)."\n";
            echo "-- sales_history and inventory_receipts are intentionally excluded --\n";
            echo "-- both are imported data with their own source CSV, not written by the app.\n";
            echo "-- See BackupController::BACKUP_TABLES for the full reasoning.\n\n";
            echo "SET NAMES utf8mb4;\n";
            echo "SET FOREIGN_KEY_CHECKS=0;\n\n";

            $pdo = DB::connection()->getPdo();

            foreach ($tables as $table) {
                $createRow = (array) DB::selectOne("SHOW CREATE TABLE `{$table}`");
                $createSql = $createRow['Create Table'] ?? reset($createRow);

                echo "-- --------------------------------------------------\n";
                echo "-- Table: {$table}\n";
                echo "-- --------------------------------------------------\n";
                echo "DROP TABLE IF EXISTS `{$table}`;\n";
                echo $createSql.";\n\n";

                // 2,000 rather than the more usual few hundred: Vercel's
                // function and Railway's MySQL aren't on the same network, so
                // each chunk pays a real round trip -- the same "public proxy
                // is slow" cost this app already documents for local seeding.
                // Measured live: 500-row chunks took ~23.5s end to end for the
                // ~28,500 rows this backup covers; fewer, larger round trips
                // cuts that down without meaningfully raising memory, since
                // the full table set is a few MB either way.
                DB::table($table)->orderBy('id')->chunkById(2000, function ($rows) use ($table, $pdo) {
                    if ($rows->isEmpty()) {
                        return;
                    }

                    $columns = array_keys((array) $rows->first());
                    $columnList = '`'.implode('`, `', $columns).'`';

                    $valueGroups = $rows->map(function ($row) use ($pdo) {
                        $values = array_map(
                            fn ($v) => $v === null ? 'NULL' : $pdo->quote((string) $v),
                            (array) $row
                        );

                        return '('.implode(', ', $values).')';
                    })->implode(",\n");

                    echo "INSERT INTO `{$table}` ({$columnList}) VALUES\n{$valueGroups};\n";
                });

                echo "\n";
            }

            echo "SET FOREIGN_KEY_CHECKS=1;\n";
        }, $filename, [
            'Content-Type' => 'application/sql',
        ]);
    }
}
